version: '3.8'

services:
  runner:
    restart: always
    build:
      context: .
      dockerfile: ./runner/Dockerfile-dev
    volumes:
      - ./runner/src:/runner/src:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DATABASE_URL=
      - NODE_ENV=development
      - MAX_RUNNING_TASKS=10
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true
