version: '3.8'

services:
  nginx:
    restart: always
    container_name: codetl-nginx
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3555:80"

  backend:
    restart: always
    container_name: codetl-backend
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - repo_data:/repos
      - uploads:/uploads
    environment:
      - DATABASE_URL=postgres://postgres:example@db:5432/postgres
      - NODE_ENV=production
      - MAX_RUNNING_TASKS=10
    env_file:
      - ./redis/.env
      - ./runner/.env

  frontend:
    container_name: codetl-frontend
    restart: always
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URL=/api

  db:
    container_name: codetl-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: codetl-redis
    restart: always
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - ./redis/.env

volumes:
  db_data:
  repo_data:
  uploads:
  redis_data:
