version: '3.8'

services:
  runner:
    restart: always
    build:
      context: .
      dockerfile: ./runner/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DATABASE_URL=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
      - MAX_RUNNING_TASKS=10
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true
