version: '3'

services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        POSTGRES_PASSWORD: example
        POSTGRES_HOST: db
    depends_on:
      - db
    ports:
        - "3555:3000"
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    db_data:
