version: '3'

services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:example@db:5432/postgres?schema=public
    depends_on:
      - db
    ports:
        - "3555:3000"
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    db_data:
