name: CI/CD for Codetierlist staging deployment (runner machine(s))

on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  deploy:
    runs-on: dev_runner
    steps:
      - uses: actions/checkout@v2

      - name: create redis env files
        run: echo "${{ secrets.REDIS_PASSWORD }}" > ./redis/.env;

      - name: create runner env files
        run: echo "${{ secrets.REDIS_HOSTPORT_DEV }}" > ./runner/.env;

      - name: compose build runners
        run: docker compose -f docker-compose-runner.yml build --pull

      - name: compose up runners
        run: docker compose -f docker-compose-runner.yml up -d
