on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  deploy:
    runs-on: dev
    steps:
      - uses: actions/checkout@v2
      
      - name: create env files
        run: |
          echo "${{ secrets.REDIS_PASSWORD }}" > ./redis/.env;
          
      - name: compose build
        run: docker compose build
      - name: compose build runners
        run: docker compose -f docker-compose-runner.yml build


      - name: compose up
        run: docker compose up -d
      - name: compose up runners
        run: docker compose -f docker-compose-runner.yml up -d

      - name: cleanup
        run: |
          docker image prune -f
          docker builder prune -f
          docker system prune -af
