on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

#      - name: create env files
#        run: |
#          echo "${{ secrets.NEXT_ENV }}" > ./.env;

      - name: compose build
        run: docker compose build

      - name: compose up
        run: docker compose up -d

      - name: prisma migrate
        run: docker compose exec next npx prisma migrate deploy
