on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: prod
    steps:
      - uses: actions/checkout@v2

      - name: create redis env files
        run: echo "${{ secrets.REDIS_PASSWORD }}" > ./redis/.env;

      - name: create backend env files
        run: echo "${{ secrets.BACKEND_ENV }}" > ./backend/.env;

      - name: create runner env files
        run: echo "${{ secrets.BACKEND_ENV }}" > ./runner/.env;

      - name: compose build
        run: docker compose build --pull

      - name: compose build runners
        run: docker compose -f docker-compose-runner.yml build --pull

      - name: compose up
        run: docker compose up -d

      - name: compose up runners
        run: docker compose -f docker-compose-runner.yml up -d
