on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: prod2
    steps:
      - uses: actions/checkout@v2

      - name: create env files
        run: |
          echo "${{ secrets.REDIS_PASSWORD }}" > ./redis/.env;
          echo "${{ secrets.REDIS_HOSTPORT }}" > ./runner/.env;

      - name: pull docker image
        run: bash -c "docker rmi docker:dind; docker pull docker:dind"


      - name: compose build runners
        run: bash -c "docker compose -f docker-compose-runner.yml build"

      - name: compose up runners
        run: bash -c "docker compose -f docker-compose-runner.yml up -d"
